services:
  snews_pg:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=snews
      - POSTGRES_PASSWORD=snews
      - POSTGRES_DB=snews_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./snews_db/database/initialization:/docker-entrypoint-initdb.d

volumes:
  postgres_data: