services:
  snews_pg:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./snews_db/database/initialization:/docker-entrypoint-initdb.d

volumes:
  postgres_data: